name: image-build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker buildx with cloud support
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ secrets.DOCKER_ORG }}/arm-cloud-builder1"
          install: true
      - name: Build and push
        run: |
            docker buildx build --platform linux/arm64,linux/amd64 --tag $USER/cloud-build-test --push .
        env:
           USER: ${{ secrets.DOCKER_USER }}